### ISSUE TITLE
Button text overlays in-page-nav

### ISSUE THREAD

**Issue by sylvanNZ** [powershop/fluxfederation.com#17]
On the About page, the button text of DOWNLOAD BROCHURE / LET'S TALK overlays in-page-nav when scrolling down to the bottom of the page.

![image](https://user-images.githubusercontent.com/49499597/55924455-0c9fef00-5c5e-11e9-87eb-dfd486182ea4.png)

**Comment by bluefantail** [comment]
Fixed in 211b7b6
