### ISSUE TITLE
More than one nav tab stays focused at the same time

### ISSUE THREAD

**Issue by sylvanNZ** [powershop/fluxfederation.com#19]
**Steps to reproduce**
1. Go to ABOUT, SOLUTIONS or CAREERS page
2. Click 'CONTACT' tab

**Actual results**
The current page tab stays focused while the CONTACT tab goes into the focused state.

**Expected results**
Only one focused tab in nav at a time. When the CONTACT tab is focused, remove the focused state of the current page tab. 

![image](https://user-images.githubusercontent.com/49499597/55924954-f98e1e80-5c5f-11e9-9374-e51756b3aab2.png)

**Comment by dartworksnz** [comment]
This is a tricky one, because the Contact menu item, scrolls the page - giving an active state on the button, while keeping 'Current' state on the page that is open. I've set this to remove the underline for the contact button focus state.

**Comment by mathyoudawson** [comment]
@dartworksnz Can this be closed?
